apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: giros
  name: giros3
spec:
  containers:
  - image: nginx
    name: giros
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
